version: "3"
services:
  api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 3000:3000
      environment:
        - APP_PORT=3000
      volumes:
        - ./src:/var/www/api/src
